/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FaceRecognition_FaceEmbedding */

#ifndef _Included_FaceRecognition_FaceEmbedding
#define _Included_FaceRecognition_FaceEmbedding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FaceRecognition_FaceEmbedding
 * Method:    allocateMemory
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_FaceRecognition_FaceEmbedding_allocateMemory
  (JNIEnv *, jobject, jstring);

/*
 * Class:     FaceRecognition_FaceEmbedding
 * Method:    encode
 * Signature: ([BIIJ)[F
 */
JNIEXPORT jfloatArray JNICALL Java_FaceRecognition_FaceEmbedding_encode
  (JNIEnv *, jobject, jbyteArray, jint, jint, jlong);

/*
 * Class:     FaceRecognition_FaceEmbedding
 * Method:    freeMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_FaceRecognition_FaceEmbedding_freeMemory
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
